/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package kintai;

import jakarta.ws.rs.GET;
import jakarta.ws.rs.Path;

@Path("/")
public class App {

    @GET
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
    }
}
